apiVersion: v1
kind: Service
metadata:
  name: my-api-service
spec:
  type: NodePort
  selector:
    app: my-api
  ports:
    - protocol: TCP
      port: 8090       # internal Service port
      targetPort: 8090 # Pod container port
      nodePort: 30094  # external access
